(define tolerance 0.00001)
(define (fixed-point f first-guess)
  (define (close-enough? v1 v2) (< (abs (- v1 v2)) tolerance))
  (define (try guess n)
    (printf "guess ~a: ~a\n" n guess)
    (let (( next (f guess)))
      (if (close-enough? guess next)
        next
        (try next (+ n 1)))))
  (try first-guess 1))

(define (golden-ratio-f x) (+ 1 (/ 1 x)))
(define (xx-f x) (/ (log 1000) (log x)))
(define (damp f)
  (lambda (x)
    (/ (+ x (f x)) 2)))
(define damped-xx-f (damp xx-f))
